### ISSUE TITLE
Betul: precourse: InstallSoftware

### ISSUE THREAD

**Issue by betulaydinturkk** [HYF-Class22/home#12]
- [x] Create a new [deliverable issue](https://github.com/HackYourFutureBelgium/precourse/tree/main/materials/create-issue.md)
- [x] Install [software](https://github.com/HackYourFutureBelgium/precourse/tree/main/materials/install-softwares.md)
- [x] Look through [the guides](https://github.com/HackYourFutureBelgium/precourse/tree/main/materials/guides.md)
- [x] Install VS Code [extensions](https://github.com/HackYourFutureBelgium/precourse/tree/main/materials/vscode-extensions.md)
- [x] Organize your [laptop](https://github.com/HackYourFutureBelgium/precourse/tree/main/materials/organize-your-laptop.md)
- [x] Setup [GitHub](https://github.com/HackYourFutureBelgium/precourse/tree/main/materials/github-setup.md)
- [x] Setup [Git](https://github.com/HackYourFutureBelgium/precourse/tree/main/materials/git-setup.md)
- [x] Prepare for the next module [Workflows](https://github.com/HackYourFutureBelgium/precourse/tree/main/materials/workflows.md)

**Comment by bermarte** [comment]
@betulaydinturkk you need to check the boxes and select '0.Precourse' as Milestone.

**Comment by betulaydinturkk** [comment]
### **Learning Objectives**

**GitHub:**
 

- [ ] 🥚 Creating Issues: You can create a new issue in a GitHub repository using an issue template. You can correctly use labels, milestones, and assignment to make your issue findable.

- [ ]  🥚 Searching Issues: You can find issues in a repository by label, author, and milestone.

- [ ]  🥚 Project Boards: You can use issues on a GitHub project board to track your class assignments and help your classmates when they need it.

**HYF Workflows:**
 

- [ ] 🥚 Check-Ins: You can use the check-in template to track your module learning objectives, your weekly progress (and to post a retrospective at the end of the module). You create one check-in issue per module in the class repo and each Thursday you add a check-in comment to it and the label for the corresponding week. After review, we add the checked label. No need to remove previous labels either. So as an example, after a 5 week module, you would have 5 comments and 5 labels added by you.

- [ ]  🥚 Deliverables: You can create an issue for this module's deliverable and track your progress on the class project board. Each week, there are different assignments / deliverables. If it is an individual project, you create your own deliverable issue for it in the class repo. If it is a group project, the entire group creates 1 issue together in the class repo.

- [ ] 🥚 Asking for Help: You can use the help-wanted template in your class repository's Discussion board to ask for help, and to help your classmates when they are blocked.

**Your Computer:**
 

- [ ] 🥚 File System Management: You can create and organize a new folder in your personal computer for the materials you will study at HYF.

**Visual Studio Code:**
 

- [ ] 🥚 Install and manage extensions

- [ ]  🥚 Open a folder for editing

- [ ] 🥚 Create new files/folders inside of the folder

- [ ] 🥚 Edit files and save changes

**Comment by bermarte** [comment]
@betulaydinturkk 'checked-1' is for the coach, it means that we checked your issue and everything is ok.

**Comment by bermarte** [comment]
@betulaydinturkk Is it clear what you should do or do you need help to understand better?

**Comment by betulaydinturkk** [comment]
I understand the problem is that I shouldn't put space after the colon and software should not be plural.Is it true?

**Comment by bermarte** [comment]
> I understand the problem is that I shouldn't put space after the colon and software should not be plural.Is it true?

No, I'll try to explain it better, this is why I have sent you the link to [the example](https://github.com/HYF-Class22/home/issues/1).

What you have now is this (in Markdown):

```markdown
- [x] Create a new [deliverable issue]
- [x] Install 
- [x] Look throw 
- [x] Install VS Code 
- [x] Organize your 
- [x] Setup [GitHub]
- [x] Setup [Git]
- [x] Prepare for the next module [Workflows]
```
That renders to:

- [x] Create a new [deliverable issue]
- [x] Install 
- [x] Look throw 
- [x] Install VS Code 
- [x] Organize your 
- [x] Setup [GitHub]
- [x] Setup [Git]
- [x] Prepare for the next module [Workflows]

So you have problems with the markdown and your text is incomplete. In the example I provided, the markdown is the following, which is correct:

```markdown
- [x] Create a new [deliverable issue](../materials/create-issue.md)
- [x]  Install [softwares](../materials/install-softwares.md)
- [x] Look throw [the guides](../materials/guides.md)
- [x] Install VS Code [extensions](../materials/vscode-extensions.md)
- [x] Organize your [laptop](../materials/orginze-your-laptop.md)
- [x] Setup [GitHub](../materials/github-setup.md)
- [x] Setup [Git](../materials/git-setup.md)
- [x] Prepare for the next module [Workflows](../materials/workflows.md)
```
that renders to:

- [x] Create a new [deliverable issue](../materials/create-issue.md)
- [x]  Install [softwares](../materials/install-softwares.md)
- [x] Look throw [the guides](../materials/guides.md)
- [x] Install VS Code [extensions](../materials/vscode-extensions.md)
- [x] Organize your [laptop](../materials/orginze-your-laptop.md)
- [x] Setup [GitHub](../materials/github-setup.md)
- [x] Setup [Git](../materials/git-setup.md)
- [x] Prepare for the next module [Workflows](../materials/workflows.md)

**Comment by bermarte** [comment]
@betulaydinturkk I'll fix it for you.

**Comment by betulaydinturkk** [comment]
I understand now, thank you.
