### ISSUE TITLE
Lishan: precourse : InstallSoftware

### ISSUE THREAD

**Issue by Lishan6** [HYF-Class22/home#17]
1. [x] Create this issue
2. [x] Look through the guides in your class repo
3. [x] Install softwares
4. [x] Install VS Code extensions
5. [x] Organize my computer
6. [x] GitHub setup
7. [x] Git setup
8. [x] Prep work for Workflows Week 1

**Comment by bermarte** [comment]
@Lishan6 Check the title, see the [others](https://github.com/HYF-Class22/home/issues) how they did.

**Comment by bermarte** [comment]
Fix the title and then you are done.

**Comment by bermarte** [comment]
@Lishan6 you should change the title, this time I will change it for you.

**Comment by Lishan6** [comment]
@bermarte thank you and sorry

**Comment by bermarte** [comment]
> @bermarte thank you and sorry

No problem! 😄
