### ISSUE TITLE
MishaShevchenko: workflows: github-profile

### ISSUE THREAD

**Issue by MishaShevchenko** [HYF-Class22/home#60]
- [x] [repo](https://github.com/_/_)
- [x] I added a coach as a collaborator
- [x] I wrote my markdown(README.md) locally on a new branch
- [x] I pulled and merged `main` into my branch before pushing
- [x] I pushed my branch to my repo and opened a PR
- [x] I went through the PR checklist
- [x] All the CI check pass
- [x] I assigned a coach to review my PR

**Comment by bermarte** [comment]
But what is this task? The student bio or the GitHub profile? Not sure what was the original idea - by seeing that there's a README, I would say the GitHub profile.

**Comment by MishaShevchenko** [comment]
I agree with you, I need to change it
